<?php
// modules/admin/register_teacher.php - WITH FULL VALIDATION
require_once __DIR__ . '/../../includes/auth.php';
$auth = new Auth();
$auth->requireAdmin();

require_once __DIR__ . '/../../models/User.php';
$userModel = new User();

// Auto-generate teacher code (supports A-Z letters)
$autoGeneratedCode = $userModel->generateTeacherCode();

$message = '';
$error = '';
$teacher_id = null;

// =============================================
// VALIDATION FUNCTIONS
// =============================================

function validateName($name) {
    // Allow only letters A-Z, a-z, spaces, and hyphens
    if (!preg_match('/^[A-Za-z\s\-\.]+$/', $name)) {
        return "Name should only contain letters (A-Z), spaces, hyphens, or periods";
    }
    if (strlen($name) < 3) {
        return "Name must be at least 3 characters long";
    }
    return true;
}

function validatePassword($password) {
    // Password must contain letters AND numbers, minimum 5 characters
    if (strlen($password) < 5) {
        return "Password must be at least 5 characters long";
    }
    if (!preg_match('/[A-Za-z]/', $password)) {
        return "Password must contain at least one letter (A-Z)";
    }
    if (!preg_match('/[0-9]/', $password)) {
        return "Password must contain at least one number (0-9)";
    }
    return true;
}

function validatePhone($phone) {
    if (empty($phone)) {
        return true; // Phone is optional
    }
    // Remove any non-digit characters for validation
    $cleanPhone = preg_replace('/[^0-9]/', '', $phone);
    if (strlen($cleanPhone) != 13) {
        return "Phone number must be exactly 13 digits (e.g., 256789123456)";
    }
    return true;
}

function validateTeacherCode($code) {
    // Allow letters A-Z and numbers, minimum 3 characters
    if (!preg_match('/^[A-Za-z0-9]+$/', $code)) {
        return "Teacher code should only contain letters (A-Z) and numbers (0-9)";
    }
    if (strlen($code) < 3) {
        return "Teacher code must be at least 3 characters long";
    }
    return true;
}

// =============================================
// FORM SUBMISSION HANDLING
// =============================================

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $name = trim($_POST['name']);
    $email = trim($_POST['email']);
    $password = $_POST['password'];
    $phone = trim($_POST['phone']);
    $teacherCode = trim($_POST['teacher_code']);
    
    // Validate all fields
    $nameValidation = validateName($name);
    $emailValidation = filter_var($email, FILTER_VALIDATE_EMAIL);
    $passwordValidation = validatePassword($password);
    $phoneValidation = validatePhone($phone);
    $codeValidation = validateTeacherCode($teacherCode);
    
    if ($nameValidation !== true) {
        $error = $nameValidation;
    } elseif (!$emailValidation) {
        $error = "Invalid email format. Please enter a valid email address.";
    } elseif ($passwordValidation !== true) {
        $error = $passwordValidation;
    } elseif ($phoneValidation !== true) {
        $error = $phoneValidation;
    } elseif ($codeValidation !== true) {
        $error = $codeValidation;
    } else {
        // All validations passed, proceed with registration
        $result = $userModel->addTeacher($name, $email, $password, $teacherCode, $phone);
        
        if ($result) {
            // Get the newly created teacher ID
            $database = new Database();
            $conn = $database->getConnection();
            $query = "SELECT t.id FROM teachers t JOIN users u ON t.user_id = u.id WHERE u.email = :email";
            $stmt = $conn->prepare($query);
            $stmt->bindParam(':email', $email);
            $stmt->execute();
            $teacher = $stmt->fetch(PDO::FETCH_ASSOC);
            $teacher_id = $teacher['id'];
            
            $message = "✅ Teacher registered successfully! Teacher Code: " . $teacherCode;
            
            // If face enrollment is selected, redirect to enrollment
            if (isset($_POST['enroll_face']) && $_POST['enroll_face'] == 'yes') {
                header("Location: enroll_face.php?id=" . $teacher_id . "&new=1");
                exit();
            }
            
            // Generate new code for next registration
            $autoGeneratedCode = $userModel->generateTeacherCode();
            $_POST = [];
        } else {
            $error = "Failed to register teacher. Email might already exist.";
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Teacher - Admin Panel</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
        .sidebar {
            position: fixed;
            left: 0;
            top: 0;
            height: 100vh;
            width: 280px;
            background: linear-gradient(135deg, #1e3a8a, #5b21b6);
            color: white;
            z-index: 100;
        }
        .main-content {
            margin-left: 280px;
        }
        .sidebar-item {
            transition: all 0.2s;
            display: flex;
            align-items: center;
            padding: 12px 24px;
        }
        .sidebar-item:hover {
            background: rgba(255,255,255,0.1);
        }
        @media (max-width: 768px) {
            .sidebar { transform: translateX(-100%); }
            .main-content { margin-left: 0; }
        }
        .enroll-option {
            transition: all 0.3s ease;
        }
        .enroll-option:hover {
            transform: translateX(5px);
        }
        .validation-hint {
            font-size: 0.7rem;
            margin-top: 4px;
        }
        .validation-hint.valid {
            color: #22c55e;
        }
        .validation-hint.invalid {
            color: #ef4444;
        }
    </style>
</head>
<body class="bg-gray-100">
    <!-- Mobile Menu Toggle -->
    <button id="menuToggle" class="fixed top-4 left-4 z-50 bg-blue-600 text-white p-2 rounded-lg md:hidden">
        <i class="fas fa-bars text-xl"></i>
    </button>
    
    <!-- Sidebar -->
    <div class="sidebar" id="sidebar">
        <div class="p-6 border-b border-white/20">
            <div class="flex items-center space-x-3">
                <i class="fas fa-chalkboard-teacher text-3xl"></i>
                <div>
                    <h2 class="text-xl font-bold">Attendance System</h2>
                    <p class="text-xs text-blue-200">Admin Panel</p>
                </div>
            </div>
        </div>
        <div class="p-4 border-b border-white/20">
            <div class="flex items-center space-x-3">
                <div class="w-10 h-10 bg-blue-500 rounded-full flex items-center justify-center">
                    <i class="fas fa-user-shield text-xl"></i>
                </div>
                <div>
                    <p class="font-semibold"><?php echo htmlspecialchars($_SESSION['user_name']); ?></p>
                    <p class="text-xs text-blue-200">Administrator</p>
                </div>
            </div>
        </div>
        <nav class="py-4">
            <a href="dashboard.php" class="sidebar-item"><i class="fas fa-tachometer-alt w-5 mr-3"></i> Dashboard</a>
            <a href="manage_teachers.php" class="sidebar-item"><i class="fas fa-chalkboard-teacher w-5 mr-3"></i> Manage Teachers</a>
            <a href="register_teacher.php" class="sidebar-item bg-white/10"><i class="fas fa-user-plus w-5 mr-3"></i> Register Teacher</a>
            <a href="attendance.php" class="sidebar-item"><i class="fas fa-calendar-check w-5 mr-3"></i> Attendance Records</a>
            <a href="reports.php" class="sidebar-item"><i class="fas fa-chart-bar w-5 mr-3"></i> Reports</a>
            <a href="leave_requests.php" class="sidebar-item"><i class="fas fa-envelope w-5 mr-3"></i> Leave Requests</a>
            <a href="gps_settings.php" class="sidebar-item"><i class="fas fa-map-marker-alt w-5 mr-3"></i> GPS Settings</a>
            <a href="../../api/logout.php" class="sidebar-item mt-8 hover:bg-red-600"><i class="fas fa-sign-out-alt w-5 mr-3"></i> Logout</a>
        </nav>
    </div>
    
    <!-- Main Content -->
    <div class="main-content">
        <div class="p-8">
            <div class="max-w-2xl mx-auto">
                <div class="flex items-center mb-6">
                    <a href="manage_teachers.php" class="text-blue-600 hover:text-blue-800 mr-4">
                        <i class="fas fa-arrow-left"></i> Back
                    </a>
                    <h1 class="text-3xl font-bold text-gray-800">Register New Teacher</h1>
                </div>
                
                <?php if ($message): ?>
                    <div class="bg-green-100 border-l-4 border-green-500 text-green-700 p-4 mb-4 rounded shadow">
                        <i class="fas fa-check-circle mr-2"></i> <?php echo $message; ?>
                    </div>
                <?php endif; ?>
                
                <?php if ($error): ?>
                    <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 mb-4 rounded shadow">
                        <i class="fas fa-exclamation-circle mr-2"></i> <?php echo $error; ?>
                    </div>
                <?php endif; ?>
                
                <div class="bg-white rounded-xl shadow-2xl overflow-hidden">
                    <div class="bg-gradient-to-r from-blue-600 to-purple-600 p-6">
                        <h2 class="text-2xl font-bold text-white"><i class="fas fa-user-plus mr-2"></i> Teacher Information</h2>
                        <p class="text-blue-100 mt-1">Enter teacher details below</p>
                    </div>
                    
                    <div class="p-6">
                        <form method="POST" action="" id="registerForm">
                            <!-- Full Name -->
                            <div class="mb-4">
                                <label class="block text-gray-700 font-bold mb-2">
                                    Full Name * 
                                    <span class="text-xs font-normal text-gray-500">(Letters A-Z only)</span>
                                </label>
                                <input type="text" name="name" required 
                                       value="<?php echo isset($_POST['name']) ? htmlspecialchars($_POST['name']) : ''; ?>"
                                       class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-blue-500"
                                       placeholder="e.g., John Doe"
                                       pattern="[A-Za-z\s\-\.]+"
                                       title="Only letters (A-Z), spaces, hyphens, and periods allowed">
                                <p class="text-xs text-gray-500 mt-1">Only letters (A-Z), spaces, hyphens, and periods allowed. Minimum 3 characters.</p>
                            </div>
                            
                            <!-- Email -->
                            <div class="mb-4">
                                <label class="block text-gray-700 font-bold mb-2">Email Address *</label>
                                <input type="email" name="email" required 
                                       value="<?php echo isset($_POST['email']) ? htmlspecialchars($_POST['email']) : ''; ?>"
                                       class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-blue-500"
                                       placeholder="teacher@example.com">
                            </div>
                            
                            <!-- Password -->
                            <div class="mb-4">
                                <label class="block text-gray-700 font-bold mb-2">
                                    Password * 
                                    <span class="text-xs font-normal text-gray-500">(Letters + Numbers, min 5 characters)</span>
                                </label>
                                <input type="password" name="password" required 
                                       class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-blue-500"
                                       placeholder="Minimum 5 characters (letters + numbers)">
                                <div class="text-xs mt-1 space-y-1">
                                    <p id="lengthCheck" class="text-gray-500"><i class="fas fa-circle mr-1" style="font-size: 6px;"></i> At least 5 characters</p>
                                    <p id="letterCheck" class="text-gray-500"><i class="fas fa-circle mr-1" style="font-size: 6px;"></i> Contains at least one letter (A-Z)</p>
                                    <p id="numberCheck" class="text-gray-500"><i class="fas fa-circle mr-1" style="font-size: 6px;"></i> Contains at least one number (0-9)</p>
                                </div>
                            </div>
                            
                            <!-- Teacher Code -->
                            <div class="mb-4">
                                <label class="block text-gray-700 font-bold mb-2">
                                    Teacher Code 
                                    <span class="text-sm text-gray-500">(Letters A-Z + Numbers, min 3 chars)</span>
                                </label>
                                <input type="text" name="teacher_code" 
                                       value="<?php echo isset($_POST['teacher_code']) ? htmlspecialchars($_POST['teacher_code']) : $autoGeneratedCode; ?>"
                                       class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-blue-500"
                                       pattern="[A-Za-z0-9]+"
                                       title="Only letters (A-Z) and numbers (0-9) allowed">
                                <p class="text-xs text-blue-600 mt-1">
                                    <i class="fas fa-sync-alt mr-1"></i> Suggested: <?php echo $autoGeneratedCode; ?>
                                </p>
                                <p class="text-xs text-gray-500">Only letters (A-Z) and numbers (0-9) allowed. Minimum 3 characters.</p>
                            </div>
                            
                            <!-- Phone Number -->
                            <div class="mb-6">
                                <label class="block text-gray-700 font-bold mb-2">
                                    Phone Number 
                                    <span class="text-xs font-normal text-gray-500">(Optional - 13 digits exactly)</span>
                                </label>
                                <input type="tel" name="phone" 
                                       value="<?php echo isset($_POST['phone']) ? htmlspecialchars($_POST['phone']) : ''; ?>"
                                       class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:border-blue-500"
                                       placeholder="e.g., 256789123456"
                                       pattern="[0-9]{13}"
                                       title="Phone number must be exactly 13 digits">
                                <p class="text-xs text-gray-500 mt-1">Example: 256789123456 (13 digits exactly)</p>
                            </div>
                            
                            <!-- Face Enrollment Option -->
                            <div class="mb-6 p-4 bg-blue-50 rounded-lg border border-blue-200">
                                <label class="flex items-center cursor-pointer">
                                    <input type="checkbox" name="enroll_face" value="yes" class="w-5 h-5 text-blue-600 rounded focus:ring-blue-500">
                                    <span class="ml-3 font-semibold text-gray-700">
                                        <i class="fas fa-camera mr-2 text-blue-500"></i>
                                        Enroll face immediately after registration
                                    </span>
                                </label>
                                <p class="text-xs text-gray-500 mt-2 ml-8">
                                    If selected, you will be redirected to face enrollment page after successful registration.
                                </p>
                            </div>
                            
                            <div class="flex gap-4">
                                <button type="submit" class="flex-1 bg-blue-500 text-white py-2 rounded-lg font-bold hover:bg-blue-600 transition">
                                    <i class="fas fa-save mr-2"></i> Register Teacher
                                </button>
                                <button type="reset" class="flex-1 bg-gray-300 text-gray-700 py-2 rounded-lg font-bold hover:bg-gray-400 transition">
                                    <i class="fas fa-undo mr-2"></i> Clear
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
                
                <!-- Quick Tips -->
                <div class="mt-6 p-4 bg-green-50 rounded-lg border border-green-200">
                    <h3 class="font-bold text-green-800 mb-2">
                        <i class="fas fa-lightbulb mr-2"></i> Validation Rules:
                    </h3>
                    <ul class="text-sm text-green-700 space-y-1 ml-6 list-disc">
                        <li><strong>Full Name:</strong> Only letters A-Z, spaces, hyphens (minimum 3 characters)</li>
                        <li><strong>Password:</strong> Minimum 5 characters, must contain letters AND numbers</li>
                        <li><strong>Teacher Code:</strong> Only letters A-Z and numbers (minimum 3 characters)</li>
                        <li><strong>Phone Number:</strong> Exactly 13 digits (e.g., 256789123456) - Optional</li>
                        <li><strong>Email:</strong> Valid email format required</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        // Real-time password validation
        const passwordInput = document.querySelector('input[name="password"]');
        const lengthCheck = document.getElementById('lengthCheck');
        const letterCheck = document.getElementById('letterCheck');
        const numberCheck = document.getElementById('numberCheck');
        
        function validatePassword() {
            const password = passwordInput.value;
            let allValid = true;
            
            // Length check (min 5)
            if (password.length >= 5) {
                lengthCheck.innerHTML = '<i class="fas fa-check-circle text-green-500 mr-1"></i> At least 5 characters';
                lengthCheck.className = 'text-green-600';
            } else {
                lengthCheck.innerHTML = '<i class="fas fa-times-circle text-red-500 mr-1"></i> At least 5 characters';
                lengthCheck.className = 'text-red-600';
                allValid = false;
            }
            
            // Letter check
            if (/[A-Za-z]/.test(password)) {
                letterCheck.innerHTML = '<i class="fas fa-check-circle text-green-500 mr-1"></i> Contains at least one letter (A-Z)';
                letterCheck.className = 'text-green-600';
            } else {
                letterCheck.innerHTML = '<i class="fas fa-times-circle text-red-500 mr-1"></i> Contains at least one letter (A-Z)';
                letterCheck.className = 'text-red-600';
                allValid = false;
            }
            
            // Number check
            if (/[0-9]/.test(password)) {
                numberCheck.innerHTML = '<i class="fas fa-check-circle text-green-500 mr-1"></i> Contains at least one number (0-9)';
                numberCheck.className = 'text-green-600';
            } else {
                numberCheck.innerHTML = '<i class="fas fa-times-circle text-red-500 mr-1"></i> Contains at least one number (0-9)';
                numberCheck.className = 'text-red-600';
                allValid = false;
            }
        }
        
        passwordInput.addEventListener('input', validatePassword);
        
        // Mobile menu toggle
        document.getElementById('menuToggle')?.addEventListener('click', function() {
            document.getElementById('sidebar').classList.toggle('open');
        });
    </script>
</body>
</html>